name: amity_sdk
description: The SDK that enables social features such as Feeds, Groups,
  Profiles, Content Posts, and Social Media Type Interactions
version: 0.34.0
homepage: https://amity.co
documentation: https://docs.amity.co/social/flutter-beta

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  byte_util: ^3.0.0
  collection: 1.17.1
  dio: ^5.2.1+1
  fixnum: ^1.1.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mqtt_client: ^10.0.0
  path_provider: ^2.0.15
  socket_io_client: ^2.0.2
  uuid: ^3.0.7
  amity_sdk_api: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_dotenv: ^5.1.0
  flutter_lints: ^2.0.2
  freezed: ^2.3.5
  hive_generator: ^2.0.0
  hive_test: ^1.0.1
  lints: ^2.1.1
  mocktail: ^0.3.0

assets:
  - .env
  - dotenv
