name: amity_sdk
description: The SDK that enables social features such as Feeds, Groups,
  Profiles, Content Posts, and Social Media Type Interactions
version: 0.34.0
homepage: https://amity.co
documentation: https://docs.amity.co/social/flutter-beta

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  byte_util: ^3.0.0
  collection: ^1.18.0
  dio: ^5.4.0
  fixnum: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mqtt_client: ^10.0.1
  path_provider: ^2.1.2
  socket_io_client: ^2.0.3+1
  uuid: ^4.3.3
  amity_sdk_api: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_dotenv: ^5.1.0
  flutter_lints: ^3.0.1
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  hive_test: ^1.0.1
  lints: ^3.0.0
  mocktail: ^1.0.2

assets:
  - .env
  - dotenv
