name: amity_sdk
description: The SDK that enables social features such as Feeds, Groups, Profiles, Content Posts, and Social Media Type Interactions
version: 0.21.0
homepage: https://amity.co
documentation: https://docs.amity.co/social/flutter-beta

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  get_it: ^7.2.0
  dio: ^5.2.1+1
  hive_flutter: ^1.1.0
  hive: ^2.2.1
  path_provider: ^2.0.10
  mqtt_client: ^9.7.4
  http: ^0.13.4
  uuid: ^3.0.6
  socket_io_client: ^1.0.2
  fixnum: ^1.0.1
  byte_util: ^3.0.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  hive_generator: ^2.0.0
  test: ^1.21.1
  lints: ^2.0.0
  flutter_dotenv: ^5.0.2
  hive_test: ^1.0.1
  mocktail: ^0.3.0
  freezed: ^2.3.2

assets:
  - .env
  - dotenv
